version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: boutique
      POSTGRES_USER: boutique
      POSTGRES_PASSWORD: boutique
    # TODO: Add a volume to persist the database data
    # PostgreSQL stores data in /var/lib/postgresql/data
    # Syntax:
    #   volumes:
    #     - volume-name:/path/in/container
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    image: ghcr.io/synnly/teaching-shop-example-fork/boutique-backend:latest
    ports:
      - "80:8000"
    environment:
      - DATABASE_HOST=db          # Service name = hostname!
      - DATABASE_NAME=boutique
      - DATABASE_USER=boutique
      - DATABASE_PASSWORD=boutique
    depends_on:
      - db

  frontend:
    image: ghcr.io/synnly/teaching-shop-example-fork/boutique-frontend:latest
    ports:
      - "5000:80"
    depends_on:
      - backend
volumes:
  db_data:
